name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Lint with flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-broken-line flake8-bugbear flake8-builtins flake8-coding flake8-commas flake8-comprehensions flake8-eradicate flake8-isort flake8-quotes pep8-naming darglint
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --statistics
